services: 
    web-server:
      image: nginx:1.21.1
      container_name: webdev-nginx
      ports:
        - "80:80"
        - "443:443"
      networks:
        - web-dev
      volumes:
        - ./confs/servers/:/etc/nginx/conf.d/
        - ./projects:/var/www/projects
        - ./confs/ssl/:/var/www/ssl

    php:
      build:
        dockerfile: ./php.dockerfile
        context: .
      image: php:8.2-fpm
      container_name: webdev-php
      volumes: 
        - ./projects:/var/www/projects
        - ./..:/var/www
        - ./php/ini:/usr/local/etc/php 
      ports: 
        - "9000:9000"
      networks: 
        - web-dev

    db:
      image: mysql:8.0.33
      container_name: webdev-mysql
      volumes: 
        - ./confs/mysql_db:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass
      ports:
        - "3306:3306"
      networks: 
        - web-dev
      
    vue:
      image: node:14
      container_name: vue-dev
      working_dir: /app
      volumes:
        - ./my-vue-app:/app
      ports:
        - "8080:8080"
      command: npm run serve

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: webdev-phpmyadmin
      environment:
        - PMA_HOST=db
        - PMA_PORT=3306
        - PMA_ARBITRARY=1
      ports:
        - "8081:80"
      networks:
        - web-dev

networks: 
      web-dev:
        driver: bridge